### ISSUE TITLE
Support for N service(proxy) objects in a single node.

### ISSUE THREAD

**Issue by KishoreVignesh** [scalecube/scalecube-services#660]
https://github.com/scalecube/scalecube-services/blob/065d7a1bec10acdad3872a0ba5c827ae6905fd91/services-examples-parent/services-examples/src/main/java/io/scalecube/services/examples/helloworld/Example1.java#L43

In the example given above,

Only one object of GreetingServiceImpl is created and associated with the node. 

How to address the case when I need to create a new instance of GreetingServiceImpl on each proxy creation?

Any way to overcome the limitations of each service object being singleton per node?

**Comment by ronenhamias** [comment]
### from service provider side:

a single microservice node can have only one service instance with same service name 'qualifier'. 
in general you can have many microservices nodes hosting a GreetingServiceImpl or different versions GreetingServiceImpl instances of GreetingService interface running in one cluster.


for example 

```java
EnglishGreetings implements GreetingService
FrenchGreetings implements GreetingService
```

***NOTE if 2 services implements same service intreface are registerd in same microservice instance then only one will be registered and they override one another. the reason is that when a service is being registered its registered by its given name 'qualified name' 

however you can still run several microservices nodes in single jvm or many jvms.

```java
// Construct a ScaleCube node which joins the cluster hosting the Greeting Service
    Microservices ms =
        Microservices.builder()
            .discovery(
                serviceEndpoint ->
                    new ScalecubeServiceDiscovery(serviceEndpoint)
                        .options(
                            opts ->
                                opts.membership(
                                    cfg -> cfg.seedMembers(seed.discovery().address()))))
            .transport(RSocketServiceTransport::new)
            .services(new EnglishGreetings())
            .startAwait();

// Construct a ScaleCube node which joins the cluster hosting the Greeting Service
    Microservices ms1 =
        Microservices.builder()
            .discovery(
                serviceEndpoint ->
                    new ScalecubeServiceDiscovery(serviceEndpoint)
                        .options(
                            opts ->
                                opts.membership(
                                    cfg -> cfg.seedMembers(seed.discovery().address()))))
            .transport(RSocketServiceTransport::new)
            .services(new FrenchGreetings())
            .startAwait();
```


more over if the two services are not implementing the same service intrface then on microserivces instance may be used:

```java
// Construct a ScaleCube node which joins the cluster hosting the Greeting Service
    Microservices ms1 =
        Microservices.builder()
            .discovery(
                serviceEndpoint ->
                    new ScalecubeServiceDiscovery(serviceEndpoint)
                        .options(
                            opts ->
                                opts.membership(
                                    cfg -> cfg.seedMembers(seed.discovery().address()))))
            .transport(RSocketServiceTransport::new)
            .services(new Service1(), new Service2(), new Service3(), new Service4())
            .startAwait();

```

### from service consumer side.
service consumer aka proxy does not care about service impl at all so both impl 'English' and 'French' running in the cluster are actually seem to the consumer as GreetingService as they answer the same service interface.

however you can use tags and routers to attach your business metadata on them and then do some better selection when coming to consume the services.

by default if not specified otherwise round-robin selection strategy is the default behavior. please not that one can attach his own custom selection strategy. 


for example when attaching a greeting service to the microservice instance we can tag they one is `English` and second is `franch` so on selection strategy we can provide the origin of the user and select the correct instance for him.
