### ISSUE TITLE
Investigate warnings due to java.nio.channels.ClosedChannelException from rsocket client

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#743]
Subj.

```
I 0516-1500:09,790 i.s.s.t.r.RSocketClientTransport Connection closed on 127.0.1.1:39955 [rsocket-worker-4-1]
W 0516-1500:09,791 i.s.s.t.r.RSocketClientTransport Exception on closing rsocket: java.nio.channels.ClosedChannelException [rsocket-worker-4-1]
I 0516-1500:09,791 i.s.s.t.r.RSocketClientTransport Connection closed on 127.0.1.1:40267 [rsocket-worker-1-1]
W 0516-1500:09,792 i.s.s.t.r.RSocketClientTransport Exception on closing rsocket: java.nio.channels.ClosedChannelException [rsocket-worker-1-1]
I 0516-1500:09,792 i.s.s.t.r.RSocketClientTransport Connection closed on 127.0.1.1:33537 [rsocket-worker-4-1]
W 0516-1500:09,792 i.s.s.t.r.RSocketClientTransport Exception on closing rsocket: java.nio.channels.ClosedChannelException [rsocket-worker-4-1]
```

**Comment by artem-v** [comment]
Not reproducing anymore. Closing.

**Comment by josephtarbit** [comment]
I'm getting this sometimes, I've tracked it down to the connection setup payload. The JDKConnectionSetupCodec is throwing ` StreamCorruptedException invalid stream header: 00000001` when it opens the `ObjectInputStream`. This closes the connection causing a `ClosedChannelException` on the client . If you use an empty `ConnectionSetupCodec` the problem is resolved. I've tried writing and reading an integer in the `ConnectionSetupCodec` and it gets corrupted. I've only just started having this problem so I'm not sure what's causing it.

**Comment by josephtarbit** [comment]
I've investigated this further and it seems to be related to threading. When I call a service method using `subscribeOn(Schedulers.parallel())`, everything works. When I call a service method without specifying a scheduler (so on the current thread) it fails. I have a suspicion that this is related to how scalecube links services to `RSocket` instances via a `ThreadLocal` map.
